"use client";
import { useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";

type User={name:string|null;email:string};
type Lead={id:string;name:string;email:string|null;phone:string|null;company:string|null;status:string;notes:string|null};
const LANGS=["Português","English","Español","Français","Deutsch","Italiano","中文","日本語","한국어","العربية","हिन्दी","Русский","Türkçe","Nederlands","Kiswahili"];

export default function Home(){
 const router=useRouter(); const [user,setUser]=useState<User|null>(null); const [tab,setTab]=useState("agent");
 const [message,setMessage]=useState(""); const [reply,setReply]=useState(""); const [loading,setLoading]=useState(false); const [conversationId,setConversationId]=useState<string>();
 const [source,setSource]=useState("detetar automaticamente"); const [target,setTarget]=useState("English"); const [translation,setTranslation]=useState(""); const [recording,setRecording]=useState(false); const recorder=useRef<MediaRecorder|null>(null); const chunks=useRef<Blob[]>([]);
 const [leads,setLeads]=useState<Lead[]>([]); const [lead,setLead]=useState({name:"",email:"",phone:"",company:""});
 useEffect(()=>{fetch("/api/auth/me").then(async r=>{if(!r.ok){router.replace("/login");return}setUser((await r.json()).user)}).catch(()=>router.replace("/login"))},[router]);
 useEffect(()=>{if(tab==="leads") fetch("/api/leads").then(r=>r.ok?r.json():null).then(d=>d&&setLeads(d.leads||[])).catch(()=>{})},[tab]);
 async function send(){if(!message.trim())return;setLoading(true);setReply("");try{const r=await fetch("/api/chat",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({message,conversationId})});const d=await r.json();if(r.status===401){router.replace("/login");return}setReply(d.reply||d.error);if(d.conversationId)setConversationId(d.conversationId);setMessage("")}finally{setLoading(false)}}
 async function translate(){if(!message.trim())return;setLoading(true);setTranslation("");try{const r=await fetch("/api/translate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({text:message,from:source,to:target})});const d=await r.json();setTranslation(d.translation||d.error)}finally{setLoading(false)}}
 async function speak(text:string){const r=await fetch("/api/voice/speak",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({text})});if(!r.ok)return;const url=URL.createObjectURL(await r.blob());const audio=new Audio(url);await audio.play();audio.onended=()=>URL.revokeObjectURL(url)}
 async function toggleRecord(){if(recording){recorder.current?.stop();setRecording(false);return}const stream=await navigator.mediaDevices.getUserMedia({audio:true});const r=new MediaRecorder(stream);recorder.current=r;chunks.current=[];r.ondataavailable=e=>chunks.current.push(e.data);r.onstop=async()=>{stream.getTracks().forEach(t=>t.stop());const fd=new FormData();fd.append("audio",new Blob(chunks.current,{type:r.mimeType}),"voice.webm");const res=await fetch("/api/voice/transcribe",{method:"POST",body:fd});const d=await res.json();if(d.text)setMessage(prev=>prev?`${prev} ${d.text}`:d.text)};r.start();setRecording(true)}
 async function addLead(e:React.FormEvent){e.preventDefault();const r=await fetch("/api/leads",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(lead)});const d=await r.json();if(r.ok){setLeads(x=>[d.lead,...x]);setLead({name:"",email:"",phone:"",company:""})}}
 async function logout(){await fetch("/api/auth/logout",{method:"POST"});router.replace("/login")}
 if(!user)return <main className="auth"><div className="card"><div className="logo">V</div><h1>VendaIA</h1><p>A carregar a sua conta...</p></div></main>;
 return <main className="app"><aside className="sidebar"><div className="brand"><span className="logo">V</span><span>VendaIA</span></div><p className="sidecopy">Seu vendedor inteligente, disponível 24/7.</p><nav>{[["agent","🤖 Agente de vendas"],["translate","🌍 Tradutor IA"],["leads","👥 CRM de leads"],["plans","💎 Planos"]].map(([id,label])=><button key={id} className={tab===id?"nav active":"nav"} onClick={()=>setTab(id)}>{label}</button>)}</nav><div className="sidebottom"><div className="account">{user.name||user.email}<small>{user.email}</small></div><button className="logout" onClick={logout}>Sair</button></div></aside>
 <section className="main"><header className="mobiletop"><div className="brand"><span className="logo">V</span> VendaIA</div><button className="logout" onClick={logout}>Sair</button></header>
 {tab==="agent"&&<><div className="hero"><div><span className="pill">● IA ONLINE</span><h1>Venda mais com um agente que nunca dorme.</h1><p>Atenda clientes, responda dúvidas, crie argumentos de venda e faça follow-up em segundos.</p></div><div className="metric"><strong>24/7</strong><span>Disponibilidade</span></div></div><section className="panel"><div className="paneltitle"><div><h2>Agente de vendas</h2><p>Teste como o seu vendedor virtual responderia.</p></div><button className="voice" onClick={()=>toggleRecord()}>{recording?"⏹ Parar gravação":"🎙 Falar"}</button></div><textarea value={message} onChange={e=>setMessage(e.target.value)} placeholder="Ex.: Tenho uma loja de roupas. Crie uma resposta para um cliente que perguntou o preço..."/><div className="actions"><button className="primary" disabled={loading} onClick={send}>{loading?"A trabalhar...":"✨ Perguntar ao agente"}</button><button className="secondary" disabled={!reply} onClick={()=>speak(reply)}>🔊 Ouvir resposta</button></div>{reply&&<div className="answer"><div className="answerhead"><span>VendaIA</span><button onClick={()=>speak(reply)}>🔊</button></div>{reply}</div>}</section></>}
 {tab==="translate"&&<section className="panel"><div className="paneltitle"><div><h2>Tradutor de conversas</h2><p>Texto, voz e reprodução falada em vários idiomas.</p></div></div><div className="langrow"><label>De<select value={source} onChange={e=>setSource(e.target.value)}><option>detetar automaticamente</option>{LANGS.map(x=><option key={x}>{x}</option>)}</select></label><button className="swap" onClick={()=>{setSource(target);setTarget(source)}}>⇄</button><label>Para<select value={target} onChange={e=>setTarget(e.target.value)}>{LANGS.map(x=><option key={x}>{x}</option>)}</select></label></div><textarea value={message} onChange={e=>setMessage(e.target.value)} placeholder="Escreva ou grave uma frase..."/><div className="actions"><button className="primary" onClick={translate} disabled={loading}>{loading?"A traduzir...":"🌍 Traduzir"}</button><button className="secondary" onClick={toggleRecord}>{recording?"⏹ Parar":"🎙 Gravar voz"}</button></div>{translation&&<div className="answer"><div className="answerhead"><span>{target}</span><button onClick={()=>speak(translation)}>🔊</button></div>{translation}</div>}</section>}
 {tab==="leads"&&<section className="panel"><div className="paneltitle"><div><h2>CRM de leads</h2><p>Guarde os contactos que o seu agente deve acompanhar.</p></div></div><form className="leadform" onSubmit={addLead}><input placeholder="Nome *" value={lead.name} onChange={e=>setLead({...lead,name:e.target.value})} required/><input placeholder="Empresa" value={lead.company} onChange={e=>setLead({...lead,company:e.target.value})}/><input placeholder="WhatsApp / telefone" value={lead.phone} onChange={e=>setLead({...lead,phone:e.target.value})}/><input type="email" placeholder="Email" value={lead.email} onChange={e=>setLead({...lead,email:e.target.value})}/><button className="primary">+ Adicionar lead</button></form><div className="leadlist">{leads.length===0?<div className="empty">Ainda não há leads. Adicione o primeiro acima.</div>:leads.map(l=><div className="lead" key={l.id}><div><strong>{l.name}</strong><span>{l.company||"Sem empresa"} · {l.phone||l.email||"Sem contacto"}</span></div><b>{l.status}</b></div>)}</div></section>}
 {tab==="plans"&&<section className="plans"><div className="hero simple"><div><span className="pill">ESCOLHA O SEU PLANO</span><h1>Comece grátis. Escale quando vender.</h1><p>Planos preparados para Angola, Brasil, Estados Unidos e outros mercados.</p></div></div><div className="pricing"><div><h3>Starter</h3><strong>10.000 Kz</strong><span>/mês</span><p>Agente IA + tradução + CRM básico.</p><button className="secondary">Plano atual</button></div><div className="featured"><span className="popular">POPULAR</span><h3>Business</h3><strong>R$149</strong><span>/mês</span><p>Mais conversas, automações e recursos de vendas.</p><button className="primary">Escolher Business</button></div><div><h3>Pro</h3><strong>US$129</strong><span>/mês</span><p>Para equipas e empresas com alto volume.</p><button className="secondary">Falar com vendas</button></div></div></section>}
 <footer>VendaIA · IA para vendas, atendimento e comunicação global</footer></section></main>;
}